### ISSUE TITLE
jblas causes UnsatisfiedLinkError on aarch64 (m1) mac

### ISSUE THREAD

**Issue by sirno** [tgvaughan/MultiTypeTree#21]
jblas doesn't support m1 (jblas-project/jblas#134 )as @tgvaughan mentioned in CompEvol/beast2#1047

This results in the following errror.

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: 'void org.jblas.NativeBlas.dgemm(char, char, int, int, int, double, double[], int, int, double[], int, int, double, double[], int, int)'
	at org.jblas.NativeBlas.dgemm(Native Method)
	at org.jblas.SimpleBlas.gemm(SimpleBlas.java:247)
	at org.jblas.DoubleMatrix.mmuli(DoubleMatrix.java:1781)
	at org.jblas.DoubleMatrix.mmul(DoubleMatrix.java:3138)
	at org.jblas.MatrixFunctions.expm(MatrixFunctions.java:428)
	at multitypetree.operators.UniformizationRetypeOperator.getBranchTypeProb(Unknown Source)
	at multitypetree.operators.NodeShiftRetype.nonRootProposal(Unknown Source)
	at multitypetree.operators.NodeShiftRetype.proposal(Unknown Source)
	at beast.core.Operator.proposal(Unknown Source)
	at beast.core.MCMC.propagateState(Unknown Source)
	at beast.core.MCMC.doLoop(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 3 more
-- org.jblas INFO Deleting /var/folders/sl/b99vml7s45q3zx3wb1fqvq240000gp/T/jblas15640803248391520753
```

**Comment by tgvaughan** [comment]
Thanks Nicolas :)

**Comment by sirno** [comment]
Looks like this one should work on arm64. https://github.com/jblas-project/jblas/releases/tag/jblas-1.2.5

**Comment by sirno** [comment]
Actually I just checked again, and it looks like version 1.2.5 should work on arm64, which is one minor version higher than what is packaged with mtt. https://github.com/jblas-project/jblas/pull/118

**Comment by triple-jay** [comment]
> Actually I just checked again, and it looks like version 1.2.5 should work on arm64, which is one minor version higher than what is packaged with mtt. [jblas-project/jblas#118](https://github.com/jblas-project/jblas/pull/118)

Hi, I'm running into the same issue—were you able to solve this? I tried replacing the jblas 1.2.4 jar file with jblas 1.2.5 and still ran into the same issue.

**Comment by tgvaughan** [comment]
Hi @triple-jay, I've just released a new version of MTT which includes (and is compiled against) the new jblas.  Maybe this helps get things working on your system?

**Comment by triple-jay** [comment]
Thank you for your quick response and help! Unfortunately, it still is giving the same error 🥲

![Screen Shot 2023-11-30 at 3 17 46 PM](https://github.com/tgvaughan/MultiTypeTree/assets/40004551/a0261f9e-8ea4-4c20-87f4-77cafba9254c)

**Comment by tgvaughan** [comment]
Sorry to hear this. :-/ I think we're a bit stuck in this case then as far as apple silicon goes.  Unless somebody has time to port MTT to a new linear algebra library which is supported on that hardware, or to include a Java-only implementation of the matrix computations.  (This latter approach would probably incur quite a speed penalty.)

For now it seems that MTT will have to remain an intel-only package :-(

**Comment by triple-jay** [comment]
Got it thank you so much for your help :)

**Comment by jugne** [comment]
Hi, you can solve this issue by using Java JDK or JRE for x86 64-bit architecture. It's the wrong architecture, but you'll be able to use it due to [rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)). Rosetta should be preinstalled, and in my experience, it's picked up automatically. Simply download JAVA for MacOS x86 64-bit as .zip, extract it to some non-default java location and point to it when running MTT. 

This _may_ be slower than using proper Java architecture, but will work for testing/developing purposes. I do not advise to use x86 64-bit Java as system default (so still have JAVA_HOME environment variable pointing to some proper Java architecture installation).

**Comment by rbouckaert** [comment]
Curiously enough, java for ARM is in [my experience](https://www.beast2.org/2023/01/11/boosting-beast-on-apple-silicon.html) slower than Java for x86 translated with rosetta. Therefore, the recommended JRE for BEAST2 (and the one packaged in releases) is x86 based. It has been a while since I looked at it, so things may have changed.
